


#tomcat端口
server:
  port: 5001


spring:
  application:
    #指定服务名称
    name: config-server

  #配置服务注册中心
  cloud:
    config:
      server:
        git:
          #git地址
          uri: https://github.com/pomestyle/spring-config-server.git
          # git账号密码
          #username: ××××××××
          #password: ××××××××
          #本地仓库
          basedir: D:/localGit/
          #也可以使用私钥链接远程仓库
          #private-key:

# eureka 服务配置
eureka:
  client:
    registerWithEureka: false  #是否将自己注册到Eureka服务中，本身就是服务，所以无需注册
    fetchRegistry: false # 是否从Eureka 中获取注册信息
    serviceUrl:  # Eureka 客户端与Eureka服务端进行交互的地主
      defaultZone: http://127.0.0.1:6868/eureka/

  instance:
    #将自己的ip注册到eureka服务中
    prefer-ip-address: true





















