

eureka:
  client:
    registerWithEureka: false  #是否将自己注册到Eureka服务中，本身就是服务，所以无需注册
    fetchRegistry: true # 是否从Eureka 中获取注册信息
    serviceUrl:  # Eureka 客户端与Eureka服务端进行交互的地主
      defaultZone: http://127.0.0.1:6868/eureka/

server:
  port: 8080



user-server: # 这个配置是请求的服务名
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
