

#tomcat端口
server:
  port: 8081


spring:
  application:
    #指定服务名称
    name: eurekaserver_gky
  security:
    user:
      name: user
      password: user


eureka:
      client:
        registerWithEureka: true  #是否将自己注册到Eureka服务中，本身就是服务，所以无需注册
        fetchRegistry: true # 是否从Eureka 中获取注册信息
        serviceUrl:  # Eureka 客户端与Eureka服务端进行交互的地主
          defaultZone: http://127.0.0.1:6868/eureka/
      server:
        enable-self-preservation: false # 禁用eureka 自我保护机制



  instance:
    #将自己的ip注册到eureka服务中
    prefer-ip-address: true





















